apiVersion: enterprise.splunk.com/v1
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  image: docker.io/splunk/splunk:$SPLUNK_VERSION
  defaults: |-
    splunk:
      apps_location:
        - $SC4S_INDEX_URL
